### ISSUE TITLE
Create Photographers' profile page

### ISSUE THREAD

**Issue by Mammarrazzi** [Mammarrazzi/website#21]
1. With photographer's URL, www.mammarrazi.com/_______
2. With their profile picture, a bio, some photos they uploaded and a calendar that customers can book them. 
![screen shot 2017-04-17 at 10 34 55 am](https://cloud.githubusercontent.com/assets/25995432/25156556/28c02832-2450-11e7-80ed-d0573eb1ecbe.png)

**Comment by Mammarrazzi** [comment]
Hi Eugene, where can we see the photographer page on the website? Is it created already?

**Comment by uicomponent** [comment]
Yes-  I add in into menu
