### ISSUE TITLE
Some photographers' Photos are not shown when searched by code, date and city.

### ISSUE THREAD

**Issue by Mammarrazzi** [Mammarrazzi/website#29]
We have six photographers out on May 7th and uploaded a lot of photos on the website. There was no sale. We want to see if customers were able to find their photos.
When I search by the following photographers' photos by San Francisco,date 5/7/2017 and code, no gallery is shown. But if you search by code only, you will see the photos.
1. Gregorius, code 89SMLRTQ.
2. Robert, code 8PSBZTOC (Look like he entered the date 5/8/2017). But photos still are not shown when I entered 5/8/2017. 
3. Faith, code SA90KH5Q

**Comment by uicomponent** [comment]
1. He entered 5/7/2017. Gallery is showing

**Comment by uicomponent** [comment]
2. 8PSBZTOC , 5/7/2017 - photos appear. 20 items

**Comment by uicomponent** [comment]
3. SA90KH5Q , 5/7/2017 - photos appear. 

My suggestion is that you fill date incorrect. I chrome it is impossible to type date, you can only select from the calendar. Probably you can type it in another browser and I will check and try to disable it and activate calendar

**Comment by uicomponent** [comment]
Add calendar - please check

**Comment by Mammarrazzi** [comment]
Hi Eugene,

This is very interesting, because when I search by code and date, the
photos show up. When I search by code, date, and city, photos don't show
up. When you search with all the info, it works?

Best,
Emma

**Comment by Mammarrazzi** [comment]
When I search by code, date and city, the photos are still not shown. Even with the new calendar.
