### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by Mammarrazzi** [Mammarrazzi/website#30]
A couple of photographer went out shooting on May 14th, code is 9THBGFDN. When you search by code only, the photos show up. When you search by code, date and city, no photos are show.

**Comment by uicomponent** [comment]
Work on it. It is issue with Safari (may be Firefox) and with date only

**Comment by Mammarrazzi** [comment]
Search is sill not working. For example. Code: R2BID7HU. Date: May 19th. City: San Francisco. When you search by code only, the photos show up. When you search by code, date and city, no photos are show.
It's the same problem that has come up many times.

**Comment by uicomponent** [comment]
Eugene Ilinykh <eugene.ilinykh@gmail.com>
May 23 (7 days ago)

to Emma 
Try to delete and upload photos again
