### ISSUE TITLE
Phone number still needs to be changed on the website

### ISSUE THREAD

**Issue by Mammarrazzi** [Mammarrazzi/website#39]
There are two places that the phone number still need to be changed.
1. Under Contact on the top,
Phone: (415) 992-5160 needs to change to mine (408)-805-1085
2. Under Photographer's Dashboard. Under Support, 
CONTAINS A NUMBER TO CALL: +1(917)749-3410
That is Vadim's number, you can change that to mine as well. (408)-805-1085

**Comment by manadream** [comment]
@Mammarrazzi This is fixed, can you double check and close? Note: I used 408-835-1085 not 408-805-1085 as that is not you number (typo, should be 835 not 805).

**Comment by Mammarrazzi** [comment]
Good call. Thanks!
