### ISSUE TITLE
Russian words on our website

### ISSUE THREAD

**Issue by Mammarrazzi** [Mammarrazzi/website#55]
There are Russian words on our website that need to be removed under Searh page.

**Comment by uicomponent** [comment]
Please send screenshot

**Comment by uicomponent** [comment]
Emma, assign to you because as we discuss you know how to fix.

**Comment by Mammarrazzi** [comment]
Eugene, Let's use gitlab from now on. To keep our communication in one place. 
And yes, it's fixed now.
