### ISSUE TITLE
Place this text under photo 

### ISSUE THREAD

**Issue by Mammarrazzi** [Mammarrazzi/website#59]
As of right now, there is nothing on the website that tells customers what they are getting for $10.
Below the price tag $10 on a photo, place the following text,
After you purchase this photo, you will get a link to download a digital copy without the watermark.

**Comment by manadream** [comment]
@Mammarrazzi This has been completed. Can you verify and close?

**Comment by Mammarrazzi** [comment]
Yes. well done!
