### ISSUE TITLE
Changes need to be made under Registration Form 

### ISSUE THREAD

**Issue by Mammarrazzi** [Mammarrazzi/website#6]
1. Delete "Password will be send you by email." under password. We no longer send password.
2. We should specify the requirement for username and password. Photographers ask me about that. 
2. How did you hear about us, options should be "Google, Craiglist, Recruiting Website, Social Media and Other"

**Comment by uicomponent** [comment]
done

**Comment by Mammarrazzi** [comment]
I don't see the changes under the application form. :/
