### ISSUE TITLE
Clean out my Dashboard

### ISSUE THREAD

**Issue by Mammarrazzi** [Mammarrazzi/website#8]
Delete some questions that we no longer use under About Yourself, About Equipment, and Additional Info.

**Comment by manadream** [comment]
@Mammarrazzi can you specify exactly what information we no longer use (that you would like to remove)?

**Comment by Mammarrazzi** [comment]
Yes, definitely.
Under Profile, About Yourself.
Replace "Why do you like taking pictures?" with "Why do you like photography and what are some of your experiences in photography?" This is the question on application.
Replace "What are your professional goals?" with "What are some of your passions, aspirations, and professional goals?" This is the question on application.
Replace "What are your influences?" with "How would you describe your style and how can you implement it in street photography?"This is the question on application.

Delete the following,
What are your hobbies, passions, aspirations?
What are your strengths and weaknesses? 	
What charitable causes are important to you?

Under About Equipment, delete the following:
Backup body (brand model/type) 	
Backup lens (brand model/type) 	
Flash (brand model/type) 	
Total available memory card (model/type)

Under Additional Info.Delete the following:
What cameras and lenses do you like to use for street photography?
Do you prefer to work with a partner or by yourself?

**Comment by manadream** [comment]
@Mammarrazzi This has been done. Can you verify and close?

**Comment by Mammarrazzi** [comment]
Great job!
