### ISSUE TITLE
Pictures under Frequently Vidwed are blank

### ISSUE THREAD

**Issue by Mammarrazzi** [Mammarrazzi/website#9]
At the bottom of home page, under “Frequently Viewed”, the first two pictures are always blank. Need to be fixed. We should change the pictures under frequently viewed.

**Comment by Mammarrazzi** [comment]
I don't know why these two photos are blank, we need to fix this. It has been like this for a long time.

**Comment by uicomponent** [comment]
Change it to the last date photos
